### ISSUE TITLE
Does not work with django1.8

### ISSUE THREAD

**Issue by owais** [mpasternak/djorm-ext-filtered-contenttypes#3]
Querying fails on django1.8 

```
Field 'item' does not generate an automatic reverse relation and therefore cannot be used for reverse querying. If it is a GenericForeignKey, consider adding a GenericRelation.
```

**Comment by mpasternak** [comment]
Shame. I'll be trying to fix this bug probably some time later, as I'm currently still on Django 1.7. Thanks for reporting this bug and remember - patches accepted!

**Comment by owais** [comment]
@mpasternak Sure. I would have tried to submit but on a really tight schedule here. Haven't even tried to convince everyone to move to 1.8 yet. Sorry for not being able to help out :(

**Comment by phoebebright** [comment]
I had the same error in django 1.8
 
Model called Tags with generic foreign key:

      object_id = models.PositiveIntegerField(verbose_name=_('Object ID'), db_index=True)
      content_type = models.ForeignKey(
        ContentType, verbose_name=_('Content type'), related_name='%(app_label)s_%(class)s_tags')

      linked_object = GenericForeignKey()

Model called Books with generic relation:
        
        tags = GenericRelation(Tags)
also tried a longer version in desperation:
        tags = GenericRelation(Tags, content_type_field='content_type',
                       object_id_field='object_id', related_query_name='bookmarks')


Trying to do this:

       link = Tag.objects.get_or_create(linked_object = self, tag=tag_obj)


raised: FieldError: Field 'linked_object' does not generate an automatic reverse relation and therefore cannot be used for reverse querying. If it is a GenericForeignKey, consider adding a GenericRelation.


also tried this with the same result:

        try:
            link = Tag.objects.get(linked_object = self, tag=tag_obj)   <---- FieldError here
        except Tag.DoesNotExist:
            link = Tag.objects.create(linked_object = self, tag=tag_obj)


But this works:

        ct = ContentType.objects.get_for_model(self)

        link = Tag.objects.get_or_create(content_type = ct, object_id = self.id, tag=tag_obj)


Hope that helps.

**Comment by mpasternak** [comment]
Patches accepted!

**Comment by mpasternak** [comment]
Fixed, thanks.

**Comment by mohammedkhalfan** [comment]
I'm using 1.8.. how do I update to get this patch? I need it! Thank you.

**Comment by mpasternak** [comment]
How did you install?

**Comment by mohammedkhalfan** [comment]
pip3 install django

thank you

**Comment by mpasternak** [comment]
How did you install djorm-ext-filtered-contenttypes
